---
# application install
- name: PHP #Добавляем репо PHP
  become: true
  ansible.builtin.apt_repository:
    repo: 'ppa:ondrej/php'

- name: Install Packages  #Установка "пакета с пакетами"
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: "{{ wp_packages }}"

- name: Download Wordpress  #Качаем Wordpress
  ansible.builtin.get_url:   
    url: "{{ wp_get_url }}"
    dest: /tmp

- name: Extract Wordpress #Разжимаем Wordpress
  become: true
  ansible.builtin.unarchive:
    remote_src: true
    src: "/tmp/{{ wp_archive_name }}"
    dest: "{{ wp_root_dir }}"

- name: Chmod&Chown #Контрольная сверка прав на папки Wordpress
  become: true
  ansible.builtin.file:
    path: "{{ wp_root_dir }}/wordpress"
    owner: root
    group: root
    mode: '777'
    recurse: true

- name: replace nginx config #Загрузка конфиги nginx
  become: true
  ansible.builtin.template:
    src: templates/default.j2
    dest: /etc/nginx/sites-available/default

- name: Restart Nginx 1 #Перезапуск nginx
  become: true
  service:
    name: nginx
    state: restarted
    
- name: replace wordpress config  #Загрузка конфига wordpress
  become: true
  ansible.builtin.template:
    src: templates/wp-config.j2
    dest: "{{ wp_root_dir }}/wordpress/wp-config.php"
    force: true

- name: Restart Nginx 2 #Перезапуск nginx
  become: true
  service:
    name: nginx
    state: restarted