---
- name: Download and run script
  become: true
  shell: sudo curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh" | sudo bash

- name: Install runner
  become: true
  shell: sudo apt-get install gitlab-runner

- name: Set SUDOERS for gitlab-runner
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    insertafter: "^root*"
    line: "gitlab-runner ALL=(ALL:ALL) ALL"

- name: Set SUDOERS for gitlab-runner (NO PASS)
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: "gitlab-runner ALL=(ALL) NOPASSWD: ALL"

#- name: Set
#  command: sudo gitlab-runner register -n --url http://gitlab --registration-token @UBF^yfv8ej3p --executor shell
